CLS
ECHO NNNNNNNNNNNNNNNNNNNNNNNNLLLLLLLLLLLLLLLLLLLLLLLLGGGGGGGGGGGGGGGGGGGG
ECHO                             Starting Editor
ECHO                               Have fun :)!
ECHO NNNNNNNNNNNNNNNNNNNNNNNNLLLLLLLLLLLLLLLLLLLLLLLLGGGGGGGGGGGGGGGGGGGG
Binaries\Win32\UDK.exe 127.0.0.1 -log