CLS
ECHO NNNNNNNNNNNNNNNNNNNNNNNNLLLLLLLLLLLLLLLLLLLLLLLLGGGGGGGGGGGGGGGGGGGG
ECHO                             Starting Editor
ECHO                               Have fun :)!
ECHO NNNNNNNNNNNNNNNNNNNNNNNNLLLLLLLLLLLLLLLLLLLLLLLLGGGGGGGGGGGGGGGGGGGG
Binaries\Win32\UDK.exe server UDKFTrap-Playground.udk